services:
  db:
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_microservices_db
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  #auth-service:
  #  build:
  #    context: .
  #    dockerfile: ./apps/auth-service/Dockerfile
  #  restart: always
  #  depends_on:
  #    - db
  #  # REMOVE PERMISSION TO ACCESS PORT FROM OUTSIDE
  #  # ports:
  #  #   - "3001:3001"
  #  env_file:
  #    - ./apps/auth-service/.env
  #
  #todos-service:
  #  build:
  #    context: .
  #    dockerfile: ./apps/todos-service/Dockerfile
  #  restart: always
  #  depends_on:
  #    - db
  #  # REMOVE PERMISSION TO ACCESS PORT FROM OUTSIDE
  #  # ports:
  #  #   - "3002:3002"
  #  env_file:
  #    - ./apps/todos-service/.env

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    restart: always

    # REMOVE PERMISSION TO ACCESS PORT FROM OUTSIDE
    # ports:
    #   - "3000:3000"
    env_file:
      - ./apps/web/.env

  nginx:
    image: docker.io/library/nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  database_data:
