services:
  db:
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_microservices_db
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - my_network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    env_file:
      - ./apps/web/.env
    networks:
      - my_network

  nginx:
    image: docker.io/library/nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - my_network

volumes:
  database_data:

networks:
  my_network:
    driver: bridge